# Auto-merge Dependabot PRs. Requires also `.github/workflows/dependabot-auto-merge.yml`.
# See https://hackmd.io/@SkynetLabs/ryFfInNXc.

version = 1

[approve]
# note: remove the "[bot]" suffix from GitHub Bot usernames.
# Instead of "dependabot[bot]" use "dependabot".
auto_approve_usernames = ["dependabot"]
